### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Cherkes001** [zeroone2numeral2/qbittorrent-bot#10]
I configured everything as described, it was time to start, I tried to run main.py, but I got the error that is shown below:
```
home@Home-SERVER:~/qbittorrent-bot$ python main.py
  File "main.py", line 73
SyntaxError: Non-ASCII character '\xe2' in file main.py on line 74, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by zeroone2numeral2** [comment]
Make sure you are running it with python3

**Comment by Cherkes001** [comment]
Yes, for sure, python3 turned out to be necessary, but another problem appeared, could you add SOCSK5 Proxy? In Russia, Telegram seems to be “blocked”, although official clients work fine without additional effort.

**Comment by zeroone2numeral2** [comment]
@Cherkes001 you might have a look at #4 - I haven't added proxy support itself for the bot, but python-telegram-bot offers an easy way to make your bot connect to a proxy. I've linked the documentation in #4
