### ISSUE TITLE
/quick show upload state with upload speed for uploading torrents

### ISSUE THREAD

**Issue by Eng3lS** [zeroone2numeral2/qbittorrent-bot#19]
I suggest displaying active torrents in a upload-state and their speed. 
Now it always shows the download speed. ![2020-02-10_192637](https://user-images.githubusercontent.com/59923611/74171101-0a703d80-4c3f-11ea-8573-9b51b049824b.png) https://github.com/zeroone2numeral2/qbittorrent-bot/blob/master/bot/plugins/quick.py#L28-L29 
as I understood in the code, at the level of my erudition

**Comment by zeroone2numeral2** [comment]
You are right, makes sense. I will consider this a bug. Will try to find some time to fix this

**Comment by zeroone2numeral2** [comment]
Now the bot will check the torrent status and decide which speed to show:

https://github.com/zeroone2numeral2/qbittorrent-bot/blob/6c5b23edd86756d9583a8b5018354ae041437e0b/qbt/custom.py#L150-L152

It will show the upload speed when the torrent status is either `uploading` or `forcedUP`
