### ISSUE TITLE
Add Feature

### ISSUE THREAD

**Issue by alamia442** [zeroone2numeral2/qbittorrent-bot#30]
Please add send link when complete download

**Comment by zeroone2numeral2** [comment]
"Send link", what do you mean?

By the way: when a torrent is completed, the bot will send you a notification or will post a message in the channel set in the config file, under `telegram.completed_torrents_notification`

**Comment by zeroone2numeral2** [comment]
Closing as no answer was received. Feel free to reopen the issue if needed
