### ISSUE TITLE
Constant DNS lookups

### ISSUE THREAD

**Issue by agneevX** [zeroone2numeral2/qbittorrent-bot#36]
I've noticed that the bot is making a DNS resolution request every 5 seconds for `api.telegram.org`.

That's more than half a million queries a month. 

Can the IP address be cached or this fetching be slowed down significantly?

**Comment by zeroone2numeral2** [comment]
This depends on the polling frequency of `python-telegram-bot`, which honestly I ignore. The behavior can be changed by tweaking the parameters passed to [Updater.start_polling](https://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.updater.html#telegram.ext.Updater.start_polling)

I will close this issue as it depends on a third-party implementation, feel free to reopen it in case you feel there's something that should be discussed
