### ISSUE TITLE
can we deploy to Railway Or Heroku?☹️

### ISSUE THREAD

**Issue by AmirulAndalib** [zeroone2numeral2/qbittorrent-bot#42]
hi just asking if we can deploy it To railway or Heroku ? It would be helpful 🤪

**Comment by zeroone2numeral2** [comment]
I guess so but I have no idea how

**Comment by AmirulAndalib** [comment]
Please Test 😁

**Comment by zeroone2numeral2** [comment]
I don't have the time and the need to test it, I'm sorry. If you can manage to deploy it, I will be glad to accept a pull request adding the required configurations
