### ISSUE TITLE
WRITE commands: add torrent file

### ISSUE THREAD

**Issue by lycheeEng** [zeroone2numeral2/qbittorrent-bot#43]
When I sent the torrent file to telegram, the bot show message `Please send me a .torrent file`. The magnet URL is OK. All operations are done in the root account.

![image](https://user-images.githubusercontent.com/12211144/119256719-aa639780-bbf4-11eb-8b7c-ccaea5453c2a.png)

System info:
Ubuntu 18.04.5 LTS
Python 3.6.9
pip 9.0.1
qBittorrent v4.4.0alpha1

**Comment by zeroone2numeral2** [comment]
Can you forward that file to [@JsonDumpBot](https://t.me/JsonDumpBot) and paste the output here?

**Comment by lycheeEng** [comment]
Here is the output:

```json
{
  "update_id": xxx,
  "message": {
    "message_id": xxx,
    "from": {
      "id": xxx,
      "is_bot": false,
      "first_name": "xxx",
      "username": "xxx",
      "language_code": "en"
    },
    "chat": {
      "id": xxx,
      "first_name": "xxx",
      "username": "xxx",
      "type": "private"
    },
    "date": 1622073152,
    "document": {
      "file_name": "ubuntu-21.04-desktop-amd64.iso.torrent",
      "mime_type": "application/x-bittorrent",
      "file_id": "BQACAgUAAxkBAAEFjBVgrt9AsQesJtAubGJ5989LM8RTowACXAMAApfJcVU1lzghJaOWZB8E",
      "file_unique_id": "AgADXAMAApfJcVU",
      "file_size": 215416
    }
  }
}
```

Here is the torrent file:

[ubuntu-21.04-desktop-amd64.iso.torrent](https://releases.ubuntu.com/21.04/ubuntu-21.04-desktop-amd64.iso.torrent)

**Comment by zeroone2numeral2** [comment]
I downloaded the same file and the bot accepts it:

![image](https://user-images.githubusercontent.com/30071771/119781643-8c838480-becb-11eb-87b1-d375248c741e.png)

Also from the json output you posted, it looks like the file has a valid mime type. Does it happen with every torrent file, or just with that one?

**Comment by lycheeEng** [comment]
Same problems:

![Screenshot 2021-05-27 at 7 25 06 PM](https://user-images.githubusercontent.com/12211144/119818289-98019a80-bf21-11eb-87d7-58a3038b4789.png)

In the terminal, it shows:
```bash
[2021-05-27 19:24:45,220][bot.plugins.add][INFO] >>> document from xxx
```

I tested with the other server, same problems.

In `config.toml` I just changed token, admins, url, login, secret.

Did qbittorrent-bot has a parameter for detailed log?

**Comment by zeroone2numeral2** [comment]
I've added a specific handler for files which are not torrent files in 67778df

Can you update the bot with `git pull`, restart it and try again?

**Comment by lycheeEng** [comment]
The bot still shows `Please send me a .torrent file`.

In terminal(when I upload torrent file to telegram):
```bash
[2021-05-27 13:26:52,255][bot.plugins.add][INFO] >>> invalid document from xxx
[2021-05-27 13:26:52,257][bot.plugins.add][DEBUG] >>> file name: ubuntu-21.04-desktop-amd64.iso.torrent
[2021-05-27 13:26:52,258][bot.plugins.add][DEBUG] >>> mime type: application/octet-stream
```

Have this error happened before?

**Comment by zeroone2numeral2** [comment]
```
mime type: application/octet-stream
```

This is the issue apparently, the file's mime type must be `application/x-bittorrent`. What happens when you forward that file to the json bot again? What mime type does it return? It should be `application/octet-stream`

Anyway, I will add a config parameter to make the bot check the file extension instead of the mime type

**Comment by lycheeEng** [comment]
```json
{
  "update_id": xxx,
  "message": {
    "message_id": xxx,
    "from": {
      "id": xxx,
      "is_bot": false,
      "first_name": "xxx",
      "last_name": "xxx",
      "username": "xxx",
      "language_code": "en"
    },
    "chat": {
      "id": xxx,
      "first_name": "xxx",
      "last_name": "xxx",
      "username": "xxx",
      "type": "private"
    },
    "date": 1622125406,
    "document": {
      "file_name": "ubuntu-21.04-desktop-amd64.iso.torrent",
      "mime_type": "application/octet-stream",
      "file_id": "BQACAgUAAxkBAAEFjWNgr6teO1wj7aBOOjH7NxrRC8jDoQAC1AIAAvZOgVVGXDhypoCFnR8E",
      "file_unique_id": "AgAD1AIAAvZOgVU",
      "file_size": 215416
    }
  }
}
```

That's unbelievable!

I have two telegram account, this account(the bot) shows `application/octet-stream`, and another account shows `application/x-bittorrent`(I sent before)

> Here is the output:
> 
> ```json
> {
>   "update_id": xxx,
>   "message": {
>     "message_id": xxx,
>     "from": {
>       "id": xxx,
>       "is_bot": false,
>       "first_name": "xxx",
>       "username": "xxx",
>       "language_code": "en"
>     },
>     "chat": {
>       "id": xxx,
>       "first_name": "xxx",
>       "username": "xxx",
>       "type": "private"
>     },
>     "date": 1622073152,
>     "document": {
>       "file_name": "ubuntu-21.04-desktop-amd64.iso.torrent",
>       "mime_type": "application/x-bittorrent",
>       "file_id": "BQACAgUAAxkBAAEFjBVgrt9AsQesJtAubGJ5989LM8RTowACXAMAApfJcVU1lzghJaOWZB8E",
>       "file_unique_id": "AgADXAMAApfJcVU",
>       "file_size": 215416
>     }
>   }
> }
> ```
> 
> Here is the torrent file:
> 
> [ubuntu-21.04-desktop-amd64.iso.torrent](https://releases.ubuntu.com/21.04/ubuntu-21.04-desktop-amd64.iso.torrent)


I am testing using another account.

**Comment by zeroone2numeral2** [comment]
Yes I have no idea why it's happening either. Anyway, the issue is definitely with the provided mime type

Later today I will see if I can make the bot work with file extensions

**Comment by zeroone2numeral2** [comment]
The bot will accept any file that has `application/x-bittorrent` mime type or `.torrent` extension, this should solve the issue

**Comment by lycheeEng** [comment]
It works fine, thank you.
