### ISSUE TITLE
Add a special tag to torrents added via the bot

### ISSUE THREAD

**Issue by zeroone2numeral2** [zeroone2numeral2/qbittorrent-bot#45]
https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#add-new-torrent

The tag should be configured via the config file. Create the tag on startup using https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#create-tags

**Comment by zeroone2numeral2** [comment]
Tested from qBittorrent 4.3.9 (Windows 10), and it works. Need to do more tests on other version

**Comment by zeroone2numeral2** [comment]
added an api version check to prevent tags creation to raise an exception

**Comment by itsboo07** [comment]
> Tested from qBittorrent 4.3.9/api version 2.8.2 (Windows 10), and it works. Need to do more tests on other version

how to get started in windows?
