### ISSUE TITLE
Failed to parse 

### ISSUE THREAD

**Issue by draugvar** [zeroone2numeral2/qbittorrent-bot#46]
I have pulled the last commits and the bot is not working anymore. I have my qbittorent running on port 9090 but when I run the bot it says:  Failed to parse: http://127.0.0.1:9090/api/v2/app/preferences
But I change nothing into my machine.

**Comment by draugvar** [comment]
this is the whole traceback:
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import bot
  File "/home/draugvar/git/qbittorrent-bot/bot/__init__.py", line 7, in <module>
    from .jobs import notify_completed, toggle_queueing
  File "/home/draugvar/git/qbittorrent-bot/bot/jobs.py", line 8, in <module>
    from .qbtinstance import qb
  File "/home/draugvar/git/qbittorrent-bot/bot/qbtinstance.py", line 14, in <module>
    qb = CustomClient(config.qbittorrent.url, bot_username=updater.bot.username)
  File "/home/draugvar/git/qbittorrent-bot/qbt/custom.py", line 136, in __init__
    super(CustomClient, self).__init__(url=url)
  File "/home/draugvar/.local/lib/python3.8/site-packages/qbittorrent/client.py", line 27, in __init__
    check_prefs = session.get(prefs_url, verify=self.verify)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 452, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 381, in prepare_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: http://127.0.0.1:9090/api/v2/app/preferences
git:(master)

**Comment by zeroone2numeral2** [comment]
Are you sure you set the correct url in `config.toml`? The url should be `http://127.0.0.1:9090`, that is, the same format you can see from `config.example.toml`

**Comment by draugvar** [comment]
Yeah I'm totally sure, I just changed the port but the format is the same.

**Comment by draugvar** [comment]
I think that the python code append /api/... there is nothing more of url = "http://127.0.0.1:9090" inside my config file

**Comment by zeroone2numeral2** [comment]
Hmm alright, it's the request module printing the endpoint url to get the preferences during the client initialization. What qbittorrent version are you running? Remember that the bot now only supports qbittorent 4.1+, since May 2020

**Comment by draugvar** [comment]
qbittorrent-nox --version
qBittorrent v4.1.7

**Comment by zeroone2numeral2** [comment]
Can you try to run the following piece of python code?

```py
from qbittorrent import Client
qb = Client('http://127.0.0.1:9090/')
qb.login('user', 'password')
torrents = qb.torrents()
print('done')
```

replace the 'user' and 'password' strings on the third line with your qbittorrent credentials

**Comment by draugvar** [comment]
if fails with the same result as above when I call Client('http://127.0.0.1:9090/'), could be the case that i'm not authorized yet?

**Comment by zeroone2numeral2** [comment]
It looks so. You probably can't access qbittorrent's web interface from http://127.0.0.1:9090, right? It looks like the address/port is incorrect

**Comment by draugvar** [comment]
I moved on purpose qbittorrent on another port, namely the 9090, so when I use a browser on the same machine I can access to the web cli without problem.

**Comment by draugvar** [comment]
btw it worked until the last commit that I pull few days ago.

**Comment by zeroone2numeral2** [comment]
I haven't changed any piece of code related to the api. Are you able to revert to an older commit and see whether it works or not?

Regardless, the exception is raised by the `python-qBittorrent` library and the request url seems to be correct. If the snippet above raises the same exception, there's probably something mis-configured that is not related to the bot. It would be interesting to know whether you can reach the web ui or not from http://127.0.0.1:9090

**Comment by draugvar** [comment]
Yes I can :D

**Comment by zeroone2numeral2** [comment]
So I tried to google the error and I've found [this](https://stackoverflow.com/a/62763856/13350541) SO answer. Maybe updating urllib3 will help:

```
python -m pip install --upgrade urllib3
```

**Comment by draugvar** [comment]
Hey, I managed to solve this reinstalling all the requirements doing pip install --force-reinstall -r requirements.txt. I think that something messed up inside the dependencies.

**Comment by draugvar** [comment]
Sorry if I made you lose time on this issue.

**Comment by zeroone2numeral2** [comment]
No worries, glad it's solved
