### ISSUE TITLE
[Feature Request] Category option Username wise / Single category

### ISSUE THREAD

**Issue by edgehub-cloud** [zeroone2numeral2/qbittorrent-bot#48]
it will help a lot but sorting stuff in order if possible pls add it

**Comment by zeroone2numeral2** [comment]
Sorry, I don't understand what you're asking for :( can you elaborate a bit more?

**Comment by edgehub-cloud** [comment]
For example user edge adds a torrent, it will create a category for that torrent. If it possible there can be a command to make a permanent category for a specific user id
/identify edge
Will keep using the category edge associated with that I'd to the torrent.

**Comment by zeroone2numeral2** [comment]
If you're talking about tags, yes, I could add a feature that adds a tag to a specific torrent corresponding to the Telegram user that added it. There are two possible approaches to tag naming, btw:

1. this is the easiest one to implement: the tag name is the user id. User nicknames and usernames can change and the bot would create different tags for the same user if the user changes his name/username. The user ID is a static number that never changes, so using it as tag name would be the best option - although you would have to know the ID of the users who use the bot to understand who's adding what
2. the tag name is the user name, and the bots keeps a _user id -> user name_ map of its users

I will think about this

**Comment by Hellbreaker01** [comment]
Tag doesn't categories the torrent, can u do it for every x user name a  new category will be made based on the user name

**Comment by zeroone2numeral2** [comment]
Tag or category, it's the same. The points I made above stand even if we categorize torrents with categories instead of tags

**Comment by edgehub-cloud** [comment]
Yes, pls do

**Comment by Zeoka** [comment]
is possible add a category for each torrent when add it? I use radarr/sonarr and I use categories for automate the downloads

**Comment by zeroone2numeral2** [comment]
it's technically possible, I will try to look into it soon

**Comment by zeroone2numeral2** [comment]
It's not possible to set a category for torrents added through the bot, you need to change `added_torrents_category` in the config file

If it doesn't exist already, the category will be created when the bot is started
