### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by ZChuckMoris** [zeroone2numeral2/qbittorrent-bot#5]
Hello. Tell me, please, how can i add my proxy into this app? Telegram doesn't work in Russia and some other countries without proxy, so proxy support is a lot important for me. Thanks in advance!

**Comment by zeroone2numeral2** [comment]
Hello, for proxy support you should refer to [python-telegram-bot's documentation](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Working-Behind-a-Proxy). I have never worked behind a proxy so I don't have experience with that
