### ISSUE TITLE
How to use qbit web ? what did I do wrong 

### ISSUE THREAD

**Issue by bolavefasfas** [zeroone2numeral2/qbittorrent-bot#58]
![image](https://user-images.githubusercontent.com/82230241/181653441-fcfc7b12-1042-421a-a07e-af0e31818058.png)

I tried all urls 
url = "http://127.0.0.1:8080/"
&
url = "http://172.17.0.1:8080"
&
url = "http://myvpsip:8080"

but non did not open the qbit web when I tried to access it on browser

what is my mistake and how to get qbit web working ? 
but the bot did start in all cases 
How to get the web ui working and from my vps panel and ip table I made sure port 8080 is open 
I even checked it with port open checker port was open

**Comment by zeroone2numeral2** [comment]
> but non did not open the qbit web when I tried to access it on browser

This request is related to your qBittorrent's configuration, so it's out of the scope of this issues tracker. i suggest you to ask in the official forum/on reddit
